FROM docker.io/archlinux:${templateOption:imageVariant}

LABEL org.opencontainers.image.source="https://github.com/outloudvi/devcontainer-templates"
LABEL org.opencontainers.image.description="Simple Arch Linux container with base-devel packages by default"
LABEL org.opencontainers.image.licenses="MIT"

WORKDIR /workspace